<a href="https://colab.research.google.com/github/aniruddhha/100-days-of-ml/blob/main/01_day_tf_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **✅ Working with tensorflow 2.0**

In [2]:
import tensorflow as tf
print(tf.__version__)

2.9.2


# **✅ What is scalar ?**

In [3]:
scalar = tf.constant(4)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=4>

### **👉 *Dimensions of scalar***

In [4]:
scalar.ndim

0

# ✅ **What is Vector**

In [5]:
vector = tf.constant([10 , 5])
vector 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  5], dtype=int32)>

### **👉 *Dimensions of Vector***

In [6]:
vector.ndim

1

# **✅ What is Matrix**

In [7]:
matrix = tf.constant([
    [1, 3],
    [6, 9]
])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [6, 9]], dtype=int32)>

### **👉 *Dimensions of Matrix***

In [8]:
matrix.ndim

2

In [9]:
matrix_one = tf.constant([
    [8., 0.9, 7.0],
    [6, 7, 8],
    [52.34, 67.45, 89.45]
])

matrix_one

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 8.  ,  0.9 ,  7.  ],
       [ 6.  ,  7.  ,  8.  ],
       [52.34, 67.45, 89.45]], dtype=float32)>

In [10]:
matrix_one.ndim

2

# **✅ What is Tensor**

In [11]:
tensor1 = tf.constant([
    [
        [1, 3, 4],
        [2, 4,5]
    ],
    [
        [1, 5, 7],
        [6, 9, 0]  
    ],
    [
        [1, 4, 0],
        [2, 4, 5]
    ]
])
tensor1

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 3, 4],
        [2, 4, 5]],

       [[1, 5, 7],
        [6, 9, 0]],

       [[1, 4, 0],
        [2, 4, 5]]], dtype=int32)>

### **👉 *Dimensions of Tensor***

In [12]:
tensor1.ndim

3

In [13]:
# 2, 2, 2, 3, 2
tensor2 = tf.constant([
    [
        [
            [
              [1,2],
              [3,4],
              [5,6]
            ],
            [
              [1,2],
              [8, 9],
              [10, 8]
            ],
        ],
        [
           [
              [1,2],
              [3,4],
              [5,6]
            ],
            [
              [1,2],
              [8, 9],
              [10, 8]
            ] 
        ]
    ],
    [
        [
            [
              [1,2],
              [3,4],
              [5,6]
            ],
            [
              [1,2],
              [8, 9],
              [10, 8]
            ],
        ],
        [
           [
              [1,2],
              [3,4],
              [5,6]
            ],
            [
              [1,2],
              [8, 9],
              [10, 8]
            ] 
        ]
    ],

])
tensor2

<tf.Tensor: shape=(2, 2, 2, 3, 2), dtype=int32, numpy=
array([[[[[ 1,  2],
          [ 3,  4],
          [ 5,  6]],

         [[ 1,  2],
          [ 8,  9],
          [10,  8]]],


        [[[ 1,  2],
          [ 3,  4],
          [ 5,  6]],

         [[ 1,  2],
          [ 8,  9],
          [10,  8]]]],



       [[[[ 1,  2],
          [ 3,  4],
          [ 5,  6]],

         [[ 1,  2],
          [ 8,  9],
          [10,  8]]],


        [[[ 1,  2],
          [ 3,  4],
          [ 5,  6]],

         [[ 1,  2],
          [ 8,  9],
          [10,  8]]]]], dtype=int32)>

# **✅ Variables**

In [14]:
vr = tf.Variable([7, 8])
vr[0]
vr[0].assign(8)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([8, 8], dtype=int32)>

# **✅ Random Tensors**

In [15]:
tf.random.set_seed(42)

In [16]:
rnd1 = tf.random.uniform(shape = [2,3])
rnd1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.6645621 , 0.44100678, 0.3528825 ],
       [0.46448255, 0.03366041, 0.68467236]], dtype=float32)>

In [17]:
rnd2 = tf.random.normal(shape = [2])
rnd2 

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.08422458, -0.86090374], dtype=float32)>

In [18]:
rnd3 = tf.random.normal(shape = [2,1])
rnd3

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.55909735],
       [-0.5347214 ]], dtype=float32)>

In [19]:
rnd4 = tf.random.normal(shape = [2,1,1])
rnd4

<tf.Tensor: shape=(2, 1, 1), dtype=float32, numpy=
array([[[ 0.65648675]],

       [[-0.4130517 ]]], dtype=float32)>

# **✅ Shuffling the Order of elements in a tensor**

In [20]:
unshuffled = tf.constant([[1,3],
                      [4,7],
                      [9,5]])
unshuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 3],
       [4, 7],
       [9, 5]], dtype=int32)>

In [21]:
shuffled = tf.random.shuffle(unshuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 3],
       [9, 5],
       [4, 7]], dtype=int32)>

In [22]:
tf.random.set_seed(42)
shuffled = tf.random.shuffle(unshuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 7],
       [9, 5],
       [1, 3]], dtype=int32)>

In [23]:
tf.random.set_seed(42)
shuffled = tf.random.shuffle(unshuffled, seed = 42)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 3],
       [4, 7],
       [9, 5]], dtype=int32)>

# **✅ Tensors of zeros and Ones**

In [24]:
tf.ones([2,4])

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [25]:
tf.zeros(shape = (2,4))

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

# **✅ Numpy Arrays to tensors**

In [26]:
import numpy as np
numpy_A = np.arange(1, 25, dtype = np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [27]:
TA = tf.constant(numpy_A)
TA

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [28]:
TA = tf.constant(numpy_A, shape=(8,3))
TA

<tf.Tensor: shape=(8, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]], dtype=int32)>

In [29]:
TA.ndim

2

In [30]:
TA = tf.constant(numpy_A, shape=(3, 2, 2, 2))
TA

<tf.Tensor: shape=(3, 2, 2, 2), dtype=int32, numpy=
array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]],


       [[[17, 18],
         [19, 20]],

        [[21, 22],
         [23, 24]]]], dtype=int32)>

In [31]:
TA.ndim

4

# **✅ Getting Information From Tensors**

In [32]:
ones = tf.ones(shape=(2, 3, 4, 5))
ones

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [33]:
ones[1]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)>

In [34]:
ones[1][0]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [35]:
ones[1][0][1]

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 1., 1., 1., 1.], dtype=float32)>

In [36]:
ones[1][0][1][0]

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [37]:
ones[1][0][1][0].numpy()

1.0

In [38]:
print(ones.shape)
print(ones.ndim)
tf.size(ones)

(2, 3, 4, 5)
4


<tf.Tensor: shape=(), dtype=int32, numpy=120>

# **✅ Indexing Tensors**

In [40]:
# get first 2 elements of each dimensions
ones[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>

In [43]:
# get the first element each dimension from each index except the final one
ones[:1, :1, : , :]

<tf.Tensor: shape=(1, 1, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [44]:
rnk_two = tf.constant([[2,4],
                       [4,5]])
rnk_two.shape, rnk_two.ndim

(TensorShape([2, 2]), 2)

In [ ]:
# Get the last item of each of row of rank 2 tensor

In [45]:
rnk_two[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 5], dtype=int32)>

In [51]:
# add extra dimension
rnk_three = rnk_two[...,tf.newaxis]
rnk_three

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [4]],

       [[4],
        [5]]], dtype=int32)>

In [55]:
tf.expand_dims(rnk_two, axis = 0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[2, 4],
        [4, 5]]], dtype=int32)>