<a href="https://colab.research.google.com/github/aniruddhha/100-days-of-ml/blob/main/01_day_tf_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **✅ Working with tensorflow 2.0**

In [3]:
import tensorflow as tf
print(tf.__version__)

2.9.2


# **✅ What is scalar ?**

In [7]:
scalar = tf.constant(4)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=4>

### **👉 *Dimensions of scalar***

In [8]:
scalar.ndim

0

# ✅ **What is Vector**

In [12]:
vector = tf.constant([10 , 5])
vector 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  5], dtype=int32)>

### **👉 *Dimensions of Vector***

In [14]:
vector.ndim

1

# **✅ What is Matrix**

In [16]:
matrix = tf.constant([
    [1, 3],
    [6, 9]
])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [6, 9]], dtype=int32)>

### **👉 *Dimensions of Matrix***

In [17]:
matrix.ndim

2

In [21]:
matrix_one = tf.constant([
    [8., 0.9, 7.0],
    [6, 7, 8],
    [52.34, 67.45, 89.45]
])

matrix_one

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 8.  ,  0.9 ,  7.  ],
       [ 6.  ,  7.  ,  8.  ],
       [52.34, 67.45, 89.45]], dtype=float32)>

In [22]:
matrix_one.ndim

2

# **✅ What is Tensor**

In [41]:
tensor1 = tf.constant([
    [
        [1, 3, 4],
        [2, 4,5]
    ],
    [
        [1, 5, 7],
        [6, 9, 0]  
    ],
    [
        [1, 4, 0],
        [2, 4, 5]
    ]
])
tensor1

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 3, 4],
        [2, 4, 5]],

       [[1, 5, 7],
        [6, 9, 0]],

       [[1, 4, 0],
        [2, 4, 5]]], dtype=int32)>

### **👉 *Dimensions of Tensor***

In [42]:
tensor1.ndim

3

In [49]:
# 2, 2, 2, 3, 2
tensor2 = tf.constant([
    [
        [
            [
              [1,2],
              [3,4],
              [5,6]
            ],
            [
              [1,2],
              [8, 9],
              [10, 8]
            ],
        ],
        [
           [
              [1,2],
              [3,4],
              [5,6]
            ],
            [
              [1,2],
              [8, 9],
              [10, 8]
            ] 
        ]
    ],
    [
        [
            [
              [1,2],
              [3,4],
              [5,6]
            ],
            [
              [1,2],
              [8, 9],
              [10, 8]
            ],
        ],
        [
           [
              [1,2],
              [3,4],
              [5,6]
            ],
            [
              [1,2],
              [8, 9],
              [10, 8]
            ] 
        ]
    ],

])
tensor2

<tf.Tensor: shape=(2, 2, 2, 3, 2), dtype=int32, numpy=
array([[[[[ 1,  2],
          [ 3,  4],
          [ 5,  6]],

         [[ 1,  2],
          [ 8,  9],
          [10,  8]]],


        [[[ 1,  2],
          [ 3,  4],
          [ 5,  6]],

         [[ 1,  2],
          [ 8,  9],
          [10,  8]]]],



       [[[[ 1,  2],
          [ 3,  4],
          [ 5,  6]],

         [[ 1,  2],
          [ 8,  9],
          [10,  8]]],


        [[[ 1,  2],
          [ 3,  4],
          [ 5,  6]],

         [[ 1,  2],
          [ 8,  9],
          [10,  8]]]]], dtype=int32)>

# **✅ Variables**

In [52]:
vr = tf.Variable([7, 8])
vr[0]
vr[0].assign(8)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([8, 8], dtype=int32)>

# **✅ Random Tensors**

In [58]:
tf.random.set_seed(42)

In [63]:
rnd1 = tf.random.uniform(shape = [2,3])
rnd1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.803156  , 0.49777734, 0.37054038],
       [0.9118674 , 0.637642  , 0.18209696]], dtype=float32)>

In [66]:
rnd2 = tf.random.normal(shape = [2])
rnd2 

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 1.1442094, -1.6089787], dtype=float32)>

In [68]:
rnd3 = tf.random.normal(shape = [2,1])
rnd3

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-1.5440757],
       [ 1.3154334]], dtype=float32)>

In [70]:
rnd4 = tf.random.normal(shape = [2,1,1])
rnd4

<tf.Tensor: shape=(2, 1, 1), dtype=float32, numpy=
array([[[-0.23585585]],

       [[ 0.33401316]]], dtype=float32)>

# **✅ Shuffling the Order of elements in a tensor**

In [73]:
unshuffled = tf.constant([[1,3],
                      [4,7],
                      [9,5]])
unshuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 3],
       [4, 7],
       [9, 5]], dtype=int32)>

In [86]:
shuffled = tf.random.shuffle(unshuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[9, 5],
       [4, 7],
       [1, 3]], dtype=int32)>

In [89]:
tf.random.set_seed(42)
shuffled = tf.random.shuffle(unshuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 7],
       [9, 5],
       [1, 3]], dtype=int32)>

In [92]:
tf.random.set_seed(42)
shuffled = tf.random.shuffle(unshuffled, seed = 42)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 3],
       [4, 7],
       [9, 5]], dtype=int32)>

# **✅ Tensors of zeros and Ones**

In [96]:
tf.ones([2,4])

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [97]:
tf.zeros(shape = (2,4))

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

# **✅ Numpy Arrays to tensors**

In [103]:
import numpy as np
numpy_A = np.arange(1, 25, dtype = np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [105]:
TA = tf.constant(numpy_A)
TA

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [112]:
TA = tf.constant(numpy_A, shape=(8,3))
TA

(<tf.Tensor: shape=(8, 3), dtype=int32, numpy=
 array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]], dtype=int32)>, 2)

In [113]:
TA.ndim

2

In [116]:
TA = tf.constant(numpy_A, shape=(3, 2, 2, 2))
TA

<tf.Tensor: shape=(3, 2, 2, 2), dtype=int32, numpy=
array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]],


       [[[17, 18],
         [19, 20]],

        [[21, 22],
         [23, 24]]]], dtype=int32)>

In [117]:
TA.ndim

4

# **✅ Getting Information From Tensors**

In [119]:
ones = tf.ones(shape=(2, 3, 4, 5))
ones

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [128]:
ones[1]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)>

In [129]:
ones[1][0]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [130]:
ones[1][0][1]

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 1., 1., 1., 1.], dtype=float32)>

In [131]:
ones[1][0][1][0]

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [132]:
ones[1][0][1][0].numpy()

1.0

In [136]:
print(ones.shape)
print(ones.ndim)
tf.size(ones)

(2, 3, 4, 5)
4


<tf.Tensor: shape=(), dtype=int32, numpy=120>