<a href="https://colab.research.google.com/github/aniruddhha/100-days-of-ml/blob/main/02_day_tf_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **✅ Working with tensorflow 2.0**

In [74]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

2.9.2


# **✅ Tensor Operations**
Element wise

In [2]:
tns = tf.constant([[1,4],
                   [2,0]])

In [4]:
tns + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 14],
       [12, 10]], dtype=int32)>

In [5]:
tns - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ -9,  -6],
       [ -8, -10]], dtype=int32)>

In [6]:
tns * 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 8],
       [4, 0]], dtype=int32)>

In [7]:
tns / 2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.5, 2. ],
       [1. , 0. ]])>

In [10]:
#GPU considered tensors
tf.math.multiply(tns, 2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 8],
       [4, 0]], dtype=int32)>

In [11]:
# alias of above 
tf.multiply(tns, 2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 8],
       [4, 0]], dtype=int32)>

# **✅ Tensor Matrix Multiplication**

In [21]:
mat1 = tf.constant([[2,3],
                    [4,5]])

mat2 = tf.constant([[4,6],
                    [3,5]])

mat3 = tf.constant([[1,2,3],
                    [3,4,5]])

In [17]:
tf.matmul(mat1, mat2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[17, 27],
       [31, 49]], dtype=int32)>

In [ ]:
mat1.shape, mat3.shape
#inner dimensions matching 
# [✅2,👉2][👉2,✅3] matching so there wont be error
# result matrix will be of size outer dimensions i.e. [2, 3]

In [24]:
tf.matmul(mat1, mat3)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 16, 21],
       [19, 28, 37]], dtype=int32)>

In [30]:
(2*1 + 3*3, 2*2 + 3*4, 2*3 + 3*5), (4*1 + 5*3 , 4*2 + 5*4 , 4*3 + 5*5)

((11, 16, 21), (19, 28, 37))

In [ ]:
#tf.matmul(mat3, mat1)
# (1*2, 2*4 , ???) so there is error

In [32]:
mat3.shape, mat1.shape
#inner dimensions are not matching 
# i.e. mat3 shape = [2,3], mat1 shape = [2,2]
# [2, 👉3][👉2, 2] ❌ not matching

(TensorShape([2, 3]), TensorShape([2, 2]))

In [38]:
# we can reshape or transponse the matrix
#transponse
tf.transpose(mat3).shape, mat1.shape

(TensorShape([3, 2]), TensorShape([2, 2]))

In [39]:
# after transpose inner dimensions are matching
# so it will perform multiplication successfully
tf.matmul(tf.transpose(mat3), mat1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[14, 18],
       [20, 26],
       [26, 34]], dtype=int32)>

In [41]:
mat_reshaped = tf.reshape(mat3, shape=(3,2))
mat_reshaped.shape, mat1.shape

(TensorShape([3, 2]), TensorShape([2, 2]))

In [42]:
## inner dimensions are matching
tf.matmul(mat_reshaped, mat1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 13],
       [18, 24],
       [28, 37]], dtype=int32)>

In [51]:
# matrix multiplication using tensordot
# axes = 1 in tensordot means matrix multiplication
tf.tensordot(mat1, mat3, axes=1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 16, 21],
       [19, 28, 37]], dtype=int32)>

In [46]:
# each element from mat1 will be multiplied with each element in mat 3
tf.tensordot(mat1, mat3, axes=0)

<tf.Tensor: shape=(2, 2, 2, 3), dtype=int32, numpy=
array([[[[ 2,  4,  6],
         [ 6,  8, 10]],

        [[ 3,  6,  9],
         [ 9, 12, 15]]],


       [[[ 4,  8, 12],
         [12, 16, 20]],

        [[ 5, 10, 15],
         [15, 20, 25]]]], dtype=int32)>

# **✅ Tensor Matrix Multiplication Practice**

In [60]:
mat1.shape, mat2.shape

(TensorShape([2, 2]), TensorShape([2, 2]))

In [63]:
mat4 = tf.constant([[1],[2], [3], [4]])

In [64]:
mat4.shape

TensorShape([4, 1])

In [67]:
tf.reshape(mat4, shape = (2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [65]:
tf.matmul(mat1, tf.reshape(mat4, shape=(2,2)))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 16],
       [19, 28]], dtype=int32)>

# **✅ Changing the datatype of Tensor**

In [69]:
B = tf.constant([[1, 2.0],
                 [2.4, 0.1]])
B.dtype

tf.float32

In [72]:
C = tf.cast(B, tf.float16)
C.dtype

tf.float16

# **✅ Aggregating Tensors**

In [75]:
A = tf.constant(np.random.randint(-100, 100, size = 50))

In [78]:
A

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ -92,   63,   71,  -62,   18,   40,   69, -100,  -66,  -28,  -88,
        -11,  -47,   15,   78,    0,   12,  -72,  -95,  -60,   70,   11,
         45,    0,  -74,  -82,  -81,  -45,   82,  -38,   74,   24,   44,
          7,   63,   10,  -80,   55,   18,   34,   63,  -21,   36,  -45,
         53,  -78,   -8,  -88,   86,  -50])>

In [77]:
tf.abs(A)

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 92,  63,  71,  62,  18,  40,  69, 100,  66,  28,  88,  11,  47,
        15,  78,   0,  12,  72,  95,  60,  70,  11,  45,   0,  74,  82,
        81,  45,  82,  38,  74,  24,  44,   7,  63,  10,  80,  55,  18,
        34,  63,  21,  36,  45,  53,  78,   8,  88,  86,  50])>

In [79]:
tf.size(A), A.shape, A.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [80]:
tf.reduce_min(A)

<tf.Tensor: shape=(), dtype=int64, numpy=-100>

In [81]:
tf.reduce_max(A)

<tf.Tensor: shape=(), dtype=int64, numpy=86>

In [82]:
tf.reduce_mean(A)

<tf.Tensor: shape=(), dtype=int64, numpy=-5>

In [83]:
tf.reduce_sum(A)

<tf.Tensor: shape=(), dtype=int64, numpy=-270>

In [99]:
B = tf.cast(A, dtype=tf.float32)
tf.math.reduce_variance(B)

<tf.Tensor: shape=(), dtype=float32, numpy=3387.2>

In [100]:

tf.math.reduce_std(B)

<tf.Tensor: shape=(), dtype=float32, numpy=58.199657>

# **✅ Positional Max and Min**

In [102]:
tf.random.set_seed(42)
A = tf.random.uniform(shape=[50])
A

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [104]:
max_pos = tf.argmax(A)

In [106]:
max_pos, A[max_pos]

(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>)

In [107]:
tf.reduce_max(A)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [110]:
min_pos = tf.argmin(A)
min_pos, A[min_pos]

(<tf.Tensor: shape=(), dtype=int64, numpy=16>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

In [111]:
tf.reduce_min(A)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

# **✅ Squeezing the tensor**

In [115]:
tf.random.set_seed(42)
A = tf.constant(tf.random.uniform(shape = [50]), shape = (1,1,1,1, 50))
A

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [117]:
B = tf.squeeze(A)
B

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

# **✅ One Hot Encoding**

In [129]:
indices = [0, 2, 3, 5]

In [130]:
tf.one_hot(indices, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [131]:
tf.one_hot(indices, depth = 4, on_value ='*', off_value='#')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'*', b'#', b'#', b'#'],
       [b'#', b'#', b'*', b'#'],
       [b'#', b'#', b'#', b'*'],
       [b'#', b'#', b'#', b'#']], dtype=object)>

# **✅ Math Operations**

In [136]:
A = tf.range(-9, 10)
A

<tf.Tensor: shape=(19,), dtype=int32, numpy=
array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9], dtype=int32)>

In [137]:
tf.math.square(A)

<tf.Tensor: shape=(19,), dtype=int32, numpy=
array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0,  1,  4,  9, 16, 25, 36, 49,
       64, 81], dtype=int32)>

In [141]:
tf.math.sqrt(tf.cast(A, dtype=tf.float16))

<tf.Tensor: shape=(19,), dtype=float16, numpy=
array([  nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,
       0.   , 1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828,
       3.   ], dtype=float16)>

In [142]:
tf.math.log(tf.cast(A, dtype=tf.float16))

<tf.Tensor: shape=(19,), dtype=float16, numpy=
array([   nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
          nan,   -inf, 0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 ,
       1.946 , 2.08  , 2.197 ], dtype=float16)>

# **✅ Tensorflow and Numpy**

In [147]:
A = tf.constant(np.array([1., 0.5, 2.3, 5.6]))
A

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([1. , 0.5, 2.3, 5.6])>

In [146]:
np_arr = np.array(A)

In [148]:
type(A), type(np_arr)

(tensorflow.python.framework.ops.EagerTensor, numpy.ndarray)

In [149]:
type(A.numpy())

numpy.ndarray

In [150]:
A = tf.constant(np.array([1., 0.5, 2.3, 5.6]))
B = tf.constant([1., 0.5, 2.3, 5.6])
A.dtype, B.dtype

(tf.float64, tf.float32)

# **✅ GPU Processing**

In [151]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [152]:
tf.config.list_physical_devices("GPU")

[]